theia/web/views/auth.py
from flask import Blueprint, request, redirect, render_template, session, url_for

import json

from theia.settings.config import config

from google.cloud import firestore
from google.cloud.firestore_v1.base_query import FieldFilter

from requests_oauthlib import OAuth2Session
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.helpers import credentials_from_session

SCOPE = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]

a = Blueprint("a", __name__, url_prefix="/", template_folder="templates")


@a.route("/login")
def login():

    client_id = config(key="oauth-client-id")
    authorization_base_url = "https://accounts.google.com/o/oauth2/v2/auth"

    google = OAuth2Session(client_id, scope=SCOPE, redirect_uri=config("redirect-uri"))

    authorization_url, state = google.authorization_url(authorization_base_url)
    session["oauth_state"] = state

    return redirect(authorization_url)


@a.route("/callback")
def callback():

    db = firestore.Client()

    client_id = config(key="oauth-client-id")
    client_secret = config(key="oauth-client-secret")
    token_url = "https://accounts.google.com/o/oauth2/token"

    google = OAuth2Session(
        client_id, state=request.args.get("state"), redirect_uri=config("redirect-uri")
    )
    token = google.fetch_token(
        token_url, client_secret=client_secret, authorization_response=request.url
    )

    r = google.get("https://www.googleapis.com/oauth2/v1/userinfo")
    info = json.loads(r.content)

    try:
        user_ref = db.collection("users")
        user = list(
            user_ref.where(filter=FieldFilter("email", "==", info["email"])).stream()
        )[0].to_dict()
        session["user"] = user
    except IndexError:
        return redirect(url_for("dash.dashboard"))

    session["oauth_token"] = token

    return redirect(url_for("dash.dashboard"))


@a.route("/", methods=("GET", "POST"))
def index():
    if "user" in session:
        return redirect(url_for("dash.dashboard"))

    return render_template("index.html")

@a.route("/start",  methods=("GET", "POST"))
def start():
    return render_template('start.html')

@a.route("/logout")
def logout():
    try:
        del session["oauth_state"]
        del session["oauth_token"]
        del session["user"]
    except KeyError:
        return redirect(url_for("a.index"))

    return redirect(url_for("a.index"))

theia/web/views/templates/admin-add-user.html
{% extends "base.html" %}

{% block content %}

<h2>Admin Dashboard</h2>

<form class="usa-form" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}

    <fieldset class="usa-fieldset">

        <label class="usa-label">Email</label>
        {{ form.email(class="usa-input")}}

        <label class="usa-label">Roles</label>
        {{ form.roles(class="usa-select")}} 

        <input class="usa-button" type="submit" value="Add">
    </fieldset>
</form>
<div></div>

{% endblock %}

theia/web/views/templates/admin-delete-user.html
{% extends "base.html" %}

{% block content %}

<h2>Admin Dashboard</h2>

Proceed with deleting <a href="{{ user_email }}">{{ user_email }}</a>?

<form class="usa-form" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}

    <fieldset class="usa-fieldset">
        <input class="usa-button" type="submit" value="Delete">
    </fieldset>
</form>

<div></div>

{% endblock %}

theia/web/views/templates/admin.html
{% extends "base.html" %}

{% block content %}

<h2>Admin Dashboard</h2>

<strong>Current Users: </strong>

{% for user in users %}
<p>{{ user['email'] }} <span><a href="{{ url_for("admin.delete_user", user_email=user['email']) }}">(delete)</a></span></p>
{% endfor %}



<hr>

<a href="{{ url_for("admin.add_user")}}">
    <button type="button" class="usa-button">Add a User</button>
</a>

<div></div>

{% endblock %}

theia/web/views/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document Processor</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uswds/3.7.1/js/uswds-init.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uswds/3.7.1/css/uswds.min.css">
    <script src="//d3js.org/d3.v4.js"></script>
</head>
<style>
    input[type="date"] {
        margin-top: 2px;
        min-width: 75%;
        min-height: 50px;
        border-width: 1px;
        border-color: #565C65;
    }
</style>
<body style="background-color: #FCFCFC;">

<div class="grid-container mobile-lg:width-mobile-lg desktop:width-tablet-lg padding-2 shadow-5">
    <div class="grid-row">
        <div class="grid-col">
            <div class="usa-overlay"></div>
                <header class="usa-header usa-header--basic">
                    <div class="usa-nav-container">
                        <div class="usa-navbar">
                            <div class="usa-logo">
                                <em class="usa-logo__text">
                                    Billion Oyster Project
                                </em>
                            </div>
                        </div>
                    </div>
                </header>
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uswds/3.7.1/js/uswds.min.js"></script>
</body>
<div class="padding-1 grid-container mobile-lg:width-mobile-lg desktop:width-tablet-lg" style="background-color: #fcfcfca1;">
    <div class="grid-row">
        <a href="/terms/privacy">Privacy</a>
    </div>
</div>


</html>

theia/web/views/templates/dashboard.html
{% extends "base.html" %}

{% block content %}

<h2>Dashboard</h2>

<a href="{{ url_for("entry.form")}}">
    <button type="button" class="usa-button">Form</button>
</a>

<div></div>

{% endblock %}

theia/web/views/templates/form.html
{% extends "base.html" %}

{% block content %}

<form class="usa-form" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <fieldset class="usa-fieldset">
        <legend class="usa-legend usa-legend--large">
            ORS Site Data Entry
        </legend>

        <label class="usa-label">Organization</label>
        {{ form.organization(class="usa-input")}}

        <label class="usa-label">Steward Name</label>
        {{ form.steward_name(class="usa-input")}}
        
        <label class="usa-label">Steward Email</label>
        {{ form.steward_email(class="usa-input")}}

        <label class="usa-label">Location</label>
        {{ form.location(class="usa-select")}}

        <label class="usa-label">Tag Shape</label>
        {{ form.tag_type(class="usa-select")}}

        <label class="usa-label">Tag Number</label>
        {{ form.tag_number(class="usa-input")}}

        <label class="usa-label">Date</label>
        {{ form.monitoring_date(class="custom-date-picker") }}

        <label class="usa-label">Total Live Oysters</label>
        {{ form.total_live_oysters(class="usa-input") }}

        <label class="usa-label">Document Image</label>
        {{ form.image(class="usa-file-input") }}

        <input class="usa-button" type="submit" value="Upload">
    </fieldset>
</form>

{% endblock %}

theia/web/views/templates/index.html
{% extends "base.html" %}

{% block content %}

<div><h2>ORS Data Submission Portal</h2></div>

<div class="margin-bottom-2">
Welcome to the Billion Oyster Project Data Submission Platform!
</div>

<div class="margin-bottom-2">
This platform provides a quick way to go through the data submission pipeline in only one form.
By utilizing computer vision, measurement data can be automatically extracted. In additon,
many other automations have been put in place to cross reference up-to-date broodstock measurement
data and site locations. Enjoy!
</div>

<a href="{{ url_for("a.start")}}">
    <button type="button" class="usa-button">Get Started</button>
</a>

<div></div>

{% endblock %}

theia/web/views/templates/privacy.html
{% extends "base.html" %}

{% block content %}


<h2>Privacy</h2>

<div>
This site uses Google Services for authorizing users based on
email address.
</div>

<div>
    <a href="/">Back Home</a>
</div>


{% endblock %}

theia/web/views/templates/result.html
{% extends "base.html" %}

{% block content %}

<p>Thank you for your submission!</p>

<a href="{{ url_for("entry.form")}}">Back to form</a>

<div id="bop_hist"></div>

<div class="margin-top-2 margin-bottom-2">y = frequency | x = shell height (mm)</div>




<div></div>
<button type="button" class="usa-button" onclick = "toCSV()">Save Data</button>

<textarea hidden id="csv">{{ df }}</textarea>

<script>
    const toCSV = () => {
        const link = document.createElement("a")
        const content = document.getElementById("csv").innerText
        const file = new Blob([content], { type: 'text/csv' });
        link.href = URL.createObjectURL(file);
        link.download = "bop.csv";
        link.click();
        URL.revokeObjectURL(link.href);
    };
</script>

<script>
// set the dimensions and margins of the graph
var margin = {top: 10, right: 30, bottom: 30, left: 40},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#bop_hist")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

const link = document.createElement("a")
const content = document.getElementById("csv").innerText
const file = new Blob([content], { type: 'text/csv' });
link.href = URL.createObjectURL(file);

// get the data
d3.csv(link.href, function(data) {

// X axis: scale and draw:
var x = d3.scaleLinear()
    .domain([0, 100])
    .range([0, width]);
svg.append("g")
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(x));

// set the parameters for the histogram
var histogram = d3.histogram()
    .value(function(d) { return d.shell_height_mm; })
    .domain(x.domain())  // then the domain of the graphic
    .thresholds(x.ticks(15)); // then the numbers of bins

// And apply this function to data to get the bins
var bins = histogram(data);

// Y axis: scale and draw:
var y = d3.scaleLinear()
    .range([height, 0]);
    y.domain([0, d3.max(bins, function(d) { return d.length; })]);   // d3.hist has to be called before the Y axis obviously
svg.append("g")
    .call(d3.axisLeft(y));

// append the bar rectangles to the svg element
svg.selectAll("rect")
    .data(bins)
    .enter()
    .append("rect")
      .attr("x", 1)
      .attr("transform", function(d) { return "translate(" + x(d.x0) + "," + y(d.length) + ")"; })
      .attr("width", function(d) { return x(d.x1) - x(d.x0) -1 ; })
      .attr("height", function(d) { return height - y(d.length); })
      .style("fill", "#69b3a2")

});
</script>

{% endblock %}

theia/web/views/templates/start.html
{% extends "base.html" %}

{% block content %}

<div><h2>ORS Data Submission Portal</h2></div>
<p>Please <a href="{{ url_for("a.login")}}">login</a> to begin data submission.</p>

{% endblock %}